"""Stored secrets

Revision ID: 005_stored_secrets
Revises: 004_connections
Create Date: 2026-07-24 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '005_stored_secrets'
down_revision: Union[str, None] = '004_connections'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stored_secrets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('nonce', sa.LargeBinary(), nullable=False),
    sa.Column('encryption_algorithm', sa.String(length=50), nullable=False),
    sa.Column('key_version', sa.String(length=50), nullable=False),
    sa.Column('payload_version', sa.Integer(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('rotated_from_secret_id', sa.Uuid(), nullable=True),
    sa.Column('last_resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rotated_from_secret_id'], ['stored_secrets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_stored_secrets_organization_id_name')
    )
    op.create_index('ix_stored_secrets_org_created_at', 'stored_secrets', ['organization_id', 'created_at'], unique=False)
    op.create_index('ix_stored_secrets_org_status', 'stored_secrets', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_stored_secrets_organization_id'), 'stored_secrets', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stored_secrets_organization_id'), table_name='stored_secrets')
    op.drop_index('ix_stored_secrets_org_status', table_name='stored_secrets')
    op.drop_index('ix_stored_secrets_org_created_at', table_name='stored_secrets')
    op.drop_table('stored_secrets')
    # ### end Alembic commands ###
